version: "3.8"

services:
    # MongoDB Service
    mongodb:
        image: mongo:4.4
        container_name: pajak-mongodb-prod
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-pajak_db}
        ports:
            - "127.0.0.1:27017:27017" # Only accessible from localhost
        volumes:
            - mongodb_data:/data/db
            - ./setup-mongodb.js:/docker-entrypoint-initdb.d/setup-mongodb.js:ro
        networks:
            - pajak-network
        command: mongod --auth --bind_ip_all

    # Next.js Application
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: pajak-nextjs-prod
        restart: unless-stopped
        ports:
            - "127.0.0.1:3000:3000" # Only accessible from localhost
        environment:
            - NODE_ENV=production
            - DATABASE_URL=mongodb://${MONGO_ROOT_USERNAME:-root}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/${MONGO_DATABASE:-pajak_db}?authSource=admin
            - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost}
            - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key-here}
            - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME:-root}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/${MONGO_DATABASE:-pajak_db}?authSource=admin
        depends_on:
            - mongodb
        networks:
            - pajak-network
        volumes:
            - ./prisma:/app/prisma:ro
        healthcheck:
<<<<<<< Updated upstream
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:3000/pajakapp/api/health",
                ]
=======
            test: ["CMD", "wget", "--no-verbose", "--tries-1", "--spider", "http://localhost:3000/pajakapp/api/health"]
>>>>>>> Stashed changes
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

volumes:
    mongodb_data:
        driver: local

networks:
    pajak-network:
        driver: bridge
